### ISSUE TITLE
incorrect local href

### ISSUE THREAD

**Issue by TallTed** [HRDKOR/hrdkorea-did#1]
https://github.com/HRDKOR/hrdkorea-did/blob/a268e7ce53fe08bd6a730dec124d190e5ff2cc2d/docs/did-method-spec.html#L186C44-L186C96

`<a href="#example-2-a-did-document-derived-from-a-did-hrdkorea">example</a>`
should be 
`<a href="#example-a-did-document-derived-from-a-did-hrdkorea">example</a>`

**Comment by HRDKOR** [comment]
We fixed it. thank you.
